# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replyMsg', '0004_auto_20180410_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
    ]
