# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replyMsg', '0005_auto_20180410_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
