# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replyMsg', '0006_auto_20180410_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField()),
            ],
        ),
    ]
